# Generated by Django 3.1.7 on 2022-10-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0018_strategy_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='bots_started',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='position_increase',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='range',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='token',
        ),
        migrations.AddField(
            model_name='positions',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='bot',
            field=models.CharField(default='off', max_length=4),
        ),
        migrations.AddField(
            model_name='strategy',
            name='difference',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='strategy',
            name='takeprofit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='stoploss',
            field=models.IntegerField(default=0),
        ),
    ]
