# Generated by Django 3.1.7 on 2022-10-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0020_auto_20221017_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop_symboll',
            name='time_in',
        ),
        migrations.AddField(
            model_name='stop_symboll',
            name='symbol',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='positions',
            name='symbol',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
