# Generated by Django 3.1.7 on 2022-10-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0021_auto_20221018_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='totp',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
